config/routes.rb
Rails.application.routes.draw do
	  
  
  resources :idiomas
  resources :capacidads
  resources :nivelacademicos
  resources :titulos
  resources :carreras
  	  resources :personas
	  resources :empresas
	  resources :postulantes do
	  		resources :exp_laborals
	  		resources :estudios
	  end
	  devise_for :users
  	  root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacidad.rb
class Capacidad < ApplicationRecord
end

app/models/carrera.rb
class Carrera < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	validates :ruc, presence: true, uniqueness: true
	validates :nombre, presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true
	validates :email, presence: true

	has_many :exp_laborals
end

app/models/estudio.rb
class Estudio < ApplicationRecord
  belongs_to :user
  belongs_to :postulante
end

app/models/exp_laboral.rb
class ExpLaboral < ApplicationRecord
	belongs_to :user
	belongs_to :postulante
	belongs_to :empresa, optional: true
end

app/models/idioma.rb
class Idioma < ApplicationRecord
end

app/models/nivelacademico.rb
class Nivelacademico < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord

end

app/models/postulante.rb
class Postulante < ApplicationRecord
	validates :cedula, presence: true, uniqueness: true
	validates :nombres, presence: true
	validates :fecha_nacimiento, presence: true
	validates :edad, presence: true
	validates :sexo, presence: true
	validates :nacionalidad, presence: true
	validates :estado_civil, presence: true
	validates :telefono, presence: true
	validates :direccion, presence: true, length: {minimum: 10}
	validates :mas_info, presence: true
	validates :idioma, presence: true

	has_many :estudios
	has_many :exp_laborals
	belongs_to :user, optional: true
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :postulantes
   has_many :estudios
    has_many :personas
   has_many :exp_laborals

end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: [:show, :edit, :update, :destroy]

  # GET /carreras
  # GET /carreras.json
  def index
    @carreras = Carrera.all
  end

  # GET /carreras/1
  # GET /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras
  # POST /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to @carrera, notice: 'Carrera was successfully created.' }
        format.json { render :show, status: :created, location: @carrera }
      else
        format.html { render :new }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1
  # PATCH/PUT /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to @carrera, notice: 'Carrera was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrera }
      else
        format.html { render :edit }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1
  # DELETE /carreras/1.json
  def destroy
    @carrera.destroy
    respond_to do |format|
      format.html { redirect_to carreras_url, notice: 'Carrera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrera_params
      params.require(:carrera).permit(:nombre)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/capacidads_helper.rb
module CapacidadsHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/postulante_helper.rb
module PostulanteHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carreras/_form.html.erb
<%= form_with(model: carrera, local: true) do |form| %>
  <% if carrera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrera.errors.count, "error") %> prohibited this carrera from being saved:</h2>

      <ul>
      <% carrera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing Carrera</h1>

<%= render 'form', carrera: @carrera %>

<%= link_to 'Show', @carrera %> |
<%= link_to 'Back', carreras_path %>

app/views/carreras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carreras</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carreras.each do |carrera| %>
      <tr>
        <td><%= carrera.nombre %></td>
        <td><%= link_to 'Show', carrera %></td>
        <td><%= link_to 'Edit', edit_carrera_path(carrera) %></td>
        <td><%= link_to 'Destroy', carrera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrera', new_carrera_path %>

app/views/carreras/new.html.erb
<h1>New Carrera</h1>

<%= render 'form', carrera: @carrera %>

<%= link_to 'Back', carreras_path %>

app/views/carreras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @carrera.nombre %>
</p>

<%= link_to 'Edit', edit_carrera_path(@carrera) %> |
<%= link_to 'Back', carreras_path %>