config/routes.rb
Rails.application.routes.draw do
	  
  
  resources :idiomas
  resources :capacidads
  resources :nivelacademicos
  resources :titulos
  resources :carreras
  	  resources :personas
	  resources :empresas
	  resources :postulantes do
	  		resources :exp_laborals
	  		resources :estudios
	  end
	  devise_for :users
  	  root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacidad.rb
class Capacidad < ApplicationRecord
end

app/models/carrera.rb
class Carrera < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	validates :ruc, presence: true, uniqueness: true
	validates :nombre, presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true
	validates :email, presence: true

	has_many :exp_laborals
end

app/models/estudio.rb
class Estudio < ApplicationRecord
  belongs_to :user
  belongs_to :postulante
end

app/models/exp_laboral.rb
class ExpLaboral < ApplicationRecord
	belongs_to :user
	belongs_to :postulante
	belongs_to :empresa, optional: true
end

app/models/idioma.rb
class Idioma < ApplicationRecord
end

app/models/nivelacademico.rb
class Nivelacademico < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord

end

app/models/postulante.rb
class Postulante < ApplicationRecord
	validates :cedula, presence: true, uniqueness: true
	validates :nombres, presence: true
	validates :fecha_nacimiento, presence: true
	validates :edad, presence: true
	validates :sexo, presence: true
	validates :nacionalidad, presence: true
	validates :estado_civil, presence: true
	validates :telefono, presence: true
	validates :direccion, presence: true, length: {minimum: 10}
	validates :mas_info, presence: true
	validates :idioma, presence: true

	has_many :estudios
	has_many :exp_laborals
	belongs_to :user, optional: true
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :postulantes
   has_many :estudios
    has_many :personas
   has_many :exp_laborals

end

app/controllers/idiomas_controller.rb
class IdiomasController < ApplicationController
  before_action :set_idioma, only: [:show, :edit, :update, :destroy]

  # GET /idiomas
  # GET /idiomas.json
  def index
    @idiomas = Idioma.all
  end

  # GET /idiomas/1
  # GET /idiomas/1.json
  def show
  end

  # GET /idiomas/new
  def new
    @idioma = Idioma.new
  end

  # GET /idiomas/1/edit
  def edit
  end

  # POST /idiomas
  # POST /idiomas.json
  def create
    @idioma = Idioma.new(idioma_params)

    respond_to do |format|
      if @idioma.save
        format.html { redirect_to @idioma, notice: 'Idioma was successfully created.' }
        format.json { render :show, status: :created, location: @idioma }
      else
        format.html { render :new }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idiomas/1
  # PATCH/PUT /idiomas/1.json
  def update
    respond_to do |format|
      if @idioma.update(idioma_params)
        format.html { redirect_to @idioma, notice: 'Idioma was successfully updated.' }
        format.json { render :show, status: :ok, location: @idioma }
      else
        format.html { render :edit }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idiomas/1
  # DELETE /idiomas/1.json
  def destroy
    @idioma.destroy
    respond_to do |format|
      format.html { redirect_to idiomas_url, notice: 'Idioma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idioma
      @idioma = Idioma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idioma_params
      params.require(:idioma).permit(:descripcion, :nivel)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/capacidads_helper.rb
module CapacidadsHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/postulante_helper.rb
module PostulanteHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/idiomas/_form.html.erb
<%= form_with(model: idioma, local: true) do |form| %>
  <% if idioma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idioma.errors.count, "error") %> prohibited this idioma from being saved:</h2>

      <ul>
      <% idioma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :nivel %>
    <%= form.text_field :nivel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/idiomas/edit.html.erb
<h1>Editing Idioma</h1>

<%= render 'form', idioma: @idioma %>

<%= link_to 'Show', @idioma %> |
<%= link_to 'Back', idiomas_path %>

app/views/idiomas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Idiomas</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Nivel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idiomas.each do |idioma| %>
      <tr>
        <td><%= idioma.descripcion %></td>
        <td><%= idioma.nivel %></td>
        <td><%= link_to 'Show', idioma %></td>
        <td><%= link_to 'Edit', edit_idioma_path(idioma) %></td>
        <td><%= link_to 'Destroy', idioma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idioma', new_idioma_path %>

app/views/idiomas/new.html.erb
<h1>New Idioma</h1>

<%= render 'form', idioma: @idioma %>

<%= link_to 'Back', idiomas_path %>

app/views/idiomas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @idioma.descripcion %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @idioma.nivel %>
</p>

<%= link_to 'Edit', edit_idioma_path(@idioma) %> |
<%= link_to 'Back', idiomas_path %>