config/routes.rb
Rails.application.routes.draw do
	  
  
  resources :idiomas
  resources :capacidads
  resources :nivelacademicos
  resources :titulos
  resources :carreras
  	  resources :personas
	  resources :empresas
	  resources :postulantes do
	  		resources :exp_laborals
	  		resources :estudios
	  end
	  devise_for :users
  	  root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/capacidad.rb
class Capacidad < ApplicationRecord
end

app/models/carrera.rb
class Carrera < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	validates :ruc, presence: true, uniqueness: true
	validates :nombre, presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true
	validates :email, presence: true

	has_many :exp_laborals
end

app/models/estudio.rb
class Estudio < ApplicationRecord
  belongs_to :user
  belongs_to :postulante
end

app/models/exp_laboral.rb
class ExpLaboral < ApplicationRecord
	belongs_to :user
	belongs_to :postulante
	belongs_to :empresa, optional: true
end

app/models/idioma.rb
class Idioma < ApplicationRecord
end

app/models/nivelacademico.rb
class Nivelacademico < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord

end

app/models/postulante.rb
class Postulante < ApplicationRecord
	validates :cedula, presence: true, uniqueness: true
	validates :nombres, presence: true
	validates :fecha_nacimiento, presence: true
	validates :edad, presence: true
	validates :sexo, presence: true
	validates :nacionalidad, presence: true
	validates :estado_civil, presence: true
	validates :telefono, presence: true
	validates :direccion, presence: true, length: {minimum: 10}
	validates :mas_info, presence: true
	validates :idioma, presence: true

	has_many :estudios
	has_many :exp_laborals
	belongs_to :user, optional: true
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :postulantes
   has_many :estudios
    has_many :personas
   has_many :exp_laborals

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/capacidads_helper.rb
module CapacidadsHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/postulante_helper.rb
module PostulanteHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_buscar.html.erb
<div class="row center-xs">
  <div class="col-xs-12 col-md-8">
	     <div class="box text-left"> 		
  			<div class="col-md-8">
  				<p>Oferta de empleo:</p>
   	           <form>
      	          <input class="form-control" type="search" placeholder="Buscar empleo" aria-label="Buscar"><br>
                  <div class="box text-right">
              <button type="button" class="btn white">Buscar</button>
            </form><br><hr>
        </div>
        <p>Oferta de empleo por Area:</p>
            <button>Comercio-Mercadeo-Ventas</button><br>
            <button>Administración de Empresas</button><br>
            <button>Construcción-Arquitectura</button><br>
            <button>Turismo-Hotelería-Gastronomía</button><br>
            <button>Analisis de Sistemas-Técnicos en Informática</button><br>
            <hr>
      </div>
  </div>
</div>

app/views/welcome/_image.html.erb
<div class="row center-xs">
  <div class="col-xs-12 col-md-10">
	    <div class="box text-left"> 
	      <%= image_tag("contratado.jpg") %>
      	</div>
  </div>
</div>

app/views/welcome/_somos.html.erb
<div class="row center-xs">
  <div class="col-xs-12 col-md-12">
	     <div class="box text-right"> 
	     	<h1>Somos Unae Busines</h1>
			<p>Te ayudamos a encontrar el puesto laboral que buscas..!</p>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1 class="center-xs">Bienvenidos a Unae Business</h1><hr>
          <div class="center-xs">
            <% if user_signed_in? %>
	             <button class="btn white"> <%= link_to "Personas registradas", personas_path  %></button>

	              <button class="btn white"> <%= link_to "Empresas", empresas_path  %></button>


	              <button class="btn white"> <%= link_to "Postulados", postulantes_path  %></button>



		    <%else%>


	            <button class="btn white"> <%= link_to "Perfil Alumno", new_persona_path  %></button>
	          
	            <button class="btn white"> <%= link_to "Registra tu empresa", new_empresa_path  %></button>
            <%end%>
          </div><hr><br>
<%= render "buscar" %><br>	
<%= render "image" %>		
<%= render "somos" %>