config/routes.rb
Rails.application.routes.draw do
	  
  
  resources :idiomas
  resources :capacidads
  resources :nivelacademicos
  resources :titulos
  resources :carreras
  	  resources :personas
	  resources :empresas
	  resources :postulantes do
	  		resources :exp_laborals
	  		resources :estudios
	  end
	  devise_for :users
  	  root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacidad.rb
class Capacidad < ApplicationRecord
end

app/models/carrera.rb
class Carrera < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	validates :ruc, presence: true, uniqueness: true
	validates :nombre, presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true
	validates :email, presence: true

	has_many :exp_laborals
end

app/models/estudio.rb
class Estudio < ApplicationRecord
  belongs_to :user
  belongs_to :postulante
end

app/models/exp_laboral.rb
class ExpLaboral < ApplicationRecord
	belongs_to :user
	belongs_to :postulante
	belongs_to :empresa, optional: true
end

app/models/idioma.rb
class Idioma < ApplicationRecord
end

app/models/nivelacademico.rb
class Nivelacademico < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord

end

app/models/postulante.rb
class Postulante < ApplicationRecord
	validates :cedula, presence: true, uniqueness: true
	validates :nombres, presence: true
	validates :fecha_nacimiento, presence: true
	validates :edad, presence: true
	validates :sexo, presence: true
	validates :nacionalidad, presence: true
	validates :estado_civil, presence: true
	validates :telefono, presence: true
	validates :direccion, presence: true, length: {minimum: 10}
	validates :mas_info, presence: true
	validates :idioma, presence: true

	has_many :estudios
	has_many :exp_laborals
	belongs_to :user, optional: true
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :postulantes
   has_many :estudios
    has_many :personas
   has_many :exp_laborals

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:usuario, :contrasenha, :confir_contra, :nombre, :apellido, :cedula, :correo, :confir_correo, :carrera, :semestre)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/capacidads_helper.rb
module CapacidadsHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/postulante_helper.rb
module PostulanteHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/personas/_form.html.erb
<div class="row center-xs">
  <div class="col-xs-12 col-md-10">
     <div class="box text-left">
     <h1> <%= name %> Solicitud de Registro </h1>
          <%= form_for(@persona) do |form| %>
      <% if @persona.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

          <ul>
          <% @persona.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <div class="field">
        <%= form.label :usuario %>
        <%= form.text_field :usuario %>
      </div>


      <div class="field">
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
      </div>

      <div class="field">
        <%= form.label :apellido %>
        <%= form.text_field :apellido %>
      </div>

      <div class="field">
        <%= form.label :cédula %>
        <%= form.number_field :cedula %>
      </div>

      <div class="field">
        <%= form.label :correo_electrónico %>
        <%= form.text_field :correo %>
      </div>

      <div class="field">
        <%= form.label :carrera %>
        <%= form.select :carrera, options_for_select(['--Selecciona la Carrera--', 'Lic. Analisis de sistemas', 'Lic. Diseño Gráfico', 'Lic. Diseño de Modas', 'Derecho', 'Lic. Contaduria pública', 'Lic. Administración de Empresas', 'Ing. Comercial', 'Lic. Comercio Internacional', 'Farmacia']) %>
      </div>

      <div class="field">
        <%= form.label :semestre_Número %>
        <%= form.number_field :semestre %>
      </div>

      <div class="actions">
        <%= form.submit "Registrame!", class:"btn white"  %>
      </div>
      <div class="field">
        <%= link_to 'Atras', root_path, class:"btn-atras" %>
      </div>
    <% end %>
</div>
</div>
</div>

app/views/personas/edit.html.erb
<div style="width:50%;margin:0 auto;">

	<%= render 'form', persona: @persona, name: "Editar" %>

	<%= link_to 'Show', @persona %> |
	<%= link_to 'Back', personas_path %>
</div>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row center-xs">
  <div class="col-xs-12 col-md-10">
     <div class="box text-left">
      <% if user_signed_in? %><h1>Personas</h1>
       <button> <%= link_to 'Crear', new_persona_path %> </button>
            <table class="table">
                
                      <thead>
                        <tr>
                          <th>Usuario</th>
                          <th>Nombre</th>
                          <th>Apellido</th>
                          <th>Cedula</th>
                          <th>Correo</th>
                          <th>Carrera</th>
                          <th>Semestre</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

          <tbody>
            <% @personas.each do |persona| %>
              <tr>
                <td><%= persona.usuario %></td>
                <td><%= persona.nombre %></td>
                <td><%= persona.apellido %></td>
                <td><%= persona.cedula %></td>
                <td><%= persona.correo %></td>
                <td><%= persona.carrera %></td>
                <td><%= persona.semestre %></td>
                <td><%= link_to 'Ver', persona %></td>
                <td><%= link_to 'Editar', edit_persona_path(persona) %></td>
                <td><%= link_to 'Eliminar', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>
        <%end%>
    </div>
  </div>
</div>

app/views/personas/new.html.erb
<div style="width:50%;margin:0 auto;">

		<%= render 'form', persona: @persona, name: "" %>

	

</div>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %><button> <%= link_to 'Crear Perfil', new_postulante_path %> </button> <%end%><br>
<p>
  <strong>Usuario:</strong>
  <%= @persona.usuario %>
</p>


<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @persona.apellido %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @persona.cedula %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @persona.correo %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @persona.carrera %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @persona.semestre %>
</p>

<%= link_to 'Editar', edit_persona_path(@persona) %> |
<%= link_to 'Atras', root_path %>